name: australia-gravity
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.6
  - pip==20.2.3
  - conda-lock==0.7.2
  - numpy==1.19.1
  - scipy==1.5.2
  - pandas==1.1.3
  - xarray==0.16.1
  - matplotlib==3.3.2
  - dask==2.30.0
  - numba==0.51.2
  - jupyter==1.0.0
  - jupyterlab==2.2.8
  - netcdf4==1.5.3
  - pygmt==0.4.1
  - gmt==6.2.0
  - pyproj===2.6.1
  - requests==2.24.0
  - tqdm==4.50.1
  # Fatiando
  - pooch==1.5.0
  - verde==1.6.0
  - harmonica==0.2.1
  - boule==0.2.0
